### ISSUE TITLE
GitBook workflow

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#16]
##### Description
- The docs are in the GitHub repo 'docs' and populated by Gitbook. Understand how Gitbook actually populates the docs from the repo
- Define a good update process including where to write and preview drafts

##### Acceptance Criteria
- Good understanding and application of Gitbook workflow 
- Defined update process in Mento development docs, including on where and how to write and preview drafts

**Comment by bayological** [comment]
@tobikuhlmann Our gitbook plan is frozen as we need to set up the billing etc. I was planning on requesting a community plan as we qualify for that. Gitbook has a bi-directional[ sync feature](https://docs.gitbook.com/getting-started/git-sync) that will keep what's deployed in line with what's in the repo and vice-versa. So to update the docs, you can either update directly in the Gitbook interface, or you can open a PR against the repo. If you use the interface, you will get to preview the changes before they are made live. If you open a PR, you can preview in VS code by right-clicking the MD file and then selecting open preview.

**Comment by tobikuhlmann** [comment]
requested a GitBook community plan for the team this morning and added updating the docs as a step in our [engineering process](https://www.notion.so/Mento-Labs-Engineering-Process-98704742218b48a7b5cb295a870515a3).
