### ISSUE TITLE
Write new Mento Docs

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#18]
### Description
- Prepare a draft and write the content of the [new docs structure](https://www.notion.so/Mento-Docs-107ecf73db844154b8fc51cf4ca6ceef)

### Definition of Done
- Got and  incorporated feedback from the team
- Good and understandable content
- Published on docs.mento.org

**Comment by tobikuhlmann** [comment]
review happens via Discord and Google Docs: https://discord.com/channels/966739027782955068/981497164817637447/1054718975667339304

**Comment by tobikuhlmann** [comment]
@bowd pls review the [developer section](https://docs.google.com/document/d/1oszW9QVpF_OeNf4du47dIMEuI9UMFNNuVMyGEYEIKxU/edit#)

**Comment by bowd** [comment]
@tobikuhlmann left some notes on the doc. I think this is a good first step. Improvement areas that can be done outside of this task:

- The diagram can be improved, notes in doc
- We should combine the user-generated notes with machine-generated notes extracted from solidity natspecs
- Links to github
