### ISSUE TITLE
Create Mento Smart Contract Architecture Diagram

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#19]
**Description**

The [current architecture diagram around smart contracts is made for McMint](https://docs.mento.org/mento-protocol-multi-collateral/developers/mento-core/architecture). We need a new one detailing Mento contract architecture. 

**Acceptance Criteria**

- [x] Diagram should be beautiful
- [x] Diagram should contain all mento protocol contracts and their interactions
- [x] Diagram should also show external dependencies (e.g.: Oracle clients)
- [x] Diagram source file should be stored in google drive and pe aptly named
- [x] Add diagram to the public docs

**Comment by philbow61** [comment]
diagram: https://drive.google.com/file/d/1KOoYhVQs6r0dCqGWPav2niM73Zp7861l/view?usp=share_link
docs: https://docs.mento.org/mento-protocol-multi-collateral/developers/mento-core/architecture

**Comment by ninocomputer** [comment]
looks good to me 👍🏼
