### ISSUE TITLE
Refine Oracle Docs

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#21]
**Description**
In docs.mento.org it is currently described what oracles are and how to run an oracle. Some oracle operations are missing: 

- For what and how the protocol uses these oracle rates
- How source trading pairs are selected and quality controlled
- What risk management is in the client and on-chain
- Link to deployed oracle pairs helm charts, for example https://github.com/celo-org/celo-monorepo/blob/master/packages/helm-charts/oracle/USDCUSD.yaml

**Acceptance Criteria**
- [x] linked oracle helm charts
- [x] section about how pairs are chosen and added
- [x] section about how and where protocol uses oracle rates
- [x] section about risk management in the client 
- [ ] oracle client diagram

**Comment by tobikuhlmann** [comment]
- Wrote the oracle pages in a [new Gitbook project 'New sections'](https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/oracles/oracles)
- Comparison to [new doc structure](https://www.notion.so/Public-Docs-Structure-Notes-d90aa71ca64a4eacbd5932d3cea1f2db)

**Comment by bowd** [comment]
Looking good 👍 left two comments:
- Padding the image
- Not sure if the intro to rate feed ids actually makes sense there, at least in the current form it feels a bit abrupt and out of context.

**Comment by tobikuhlmann** [comment]
Thanks 👍 I'm putting it back in progress and added an acceptance criteria point bc I'm working on adding a oracle client diagram. For future reviewers: just the diagram needs to be reviewed

**Comment by tobikuhlmann** [comment]
Ok build a flow chart for the oracle client: https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/developers/oracles/oracle-client#undefined

After the text has already been reviewed it's enough to just review the diagram

**Comment by philbow61** [comment]
LGTM 🚢 
left one comment
