### ISSUE TITLE
Link deployment parameters in docs

### ISSUE THREAD

**Issue by bowd** [mento-protocol/docs#22]
**Description**
For other protocols, it is hard to find out what parameters are deployed and what's on-chain. We should act on transparency and make it easy for users to find them. 

The deployment parameters are currently in the deployment repo: https://github.com/mento-protocol/mento-deployment/blob/main/script/upgrades/MU01/governance/Config.sol

But also what's on-chain could change over time. 

Maybe it is also enough for now to only link deployment parameters in the docs and not worry about keeping them up to date. Users could verify themselves with the verified contracts in the explorers. 

**Acceptnace Criteria**
- [x] Decide on a way how to share deployment parameters and keep them up to date
- [x] Link them in the docs

**Comment by philbow61** [comment]
https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/TTxQdBUOJwGkQLpLLxm8/~/changes/45/developers/deployment-parameters
