### ISSUE TITLE
Protocol Concepts - Trading Limits

### ISSUE THREAD

**Issue by bayological** [mento-protocol/docs#24]
**Description**
Add a page to the protocol concepts section that describes what trading limits are.

**Acceptance Criteria**

- [x] Page added in notion that gives an overview of trading limits

**Comment by bayological** [comment]
https://www.notion.so/Trading-Limits-P-3de58dc251b642e182d68106ab11123d

**Comment by philbow61** [comment]
LGTM 🚢 
left one comment regarding the example of cUSD to BTC trades
