### ISSUE TITLE
Protocol Concepts - Circuit Breaker

### ISSUE THREAD

**Issue by bayological** [mento-protocol/docs#25]
**Description**
Add a page to the protocol concepts section that describes what the circuit breaker is.

**Acceptance Criteria**

- [x] Page added in notion that gives an overview of the circuit breaker

**Comment by bayological** [comment]
Read me :) - https://www.notion.so/On-Chain-Circuit-Breaker-Overview-803a3868dd7d42c7868aa10f6c5cf930

**Comment by bowd** [comment]
Left a comment 👁 👃 👁
                                👄

**Comment by bayological** [comment]
![](https://www.reactiongifs.com/r/chloe.gif)
