### ISSUE TITLE
Protocol Concepts - Exchange Providers, Exchanges, & Pricing Modules

### ISSUE THREAD

**Issue by bayological** [mento-protocol/docs#26]
**Description**
Add a page to the protocol concepts section that describes Exchange Providers, Exchanges, vAMMs & Pricing Modules.

**Acceptance Criteria**

- [ ] Page added in Gitbook that gives an overview of the topic

**Comment by bayological** [comment]
@bowd I'd like to pass the baton or collaborate on this.

**Comment by bowd** [comment]
It will be my honor ser 🫡

**Comment by philbow61** [comment]
LGTM 🚢

**Comment by tobikuhlmann** [comment]
closing, done by @bowd
