### ISSUE TITLE
V2 docs skeleton in GitBook

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#28]
**Description**
Create the structure skeleton from https://www.notion.so/Public-Docs-Structure-Notes-d90aa71ca64a4eacbd5932d3cea1f2db in Gitbook new sections space https://www.notion.so/Public-Docs-Structure-Notes-d90aa71ca64a4eacbd5932d3cea1f2db

**Acceptance Criteria**
- [x] new docs structure in Gitbook 
- [x] Transfer pages that don't need to be edited or newly written

**Comment by tobikuhlmann** [comment]
How to review: 
- Does the table of contents and layout make sense to you? 
- Check against this notion page: https://www.notion.so/Public-Docs-Structure-Notes-d90aa71ca64a4eacbd5932d3cea1f2db?d=fe455605ec374cd383e8dd8884e5278f#8eddbdb9ec84470c88d3be458ee0f68f (there are some new sections in GitBook that are not in the notion page, but everything from the notion page should be in GitBook)

**Comment by philbow61** [comment]
Really like the new structure LGTM 🤩 .
I only saw, that the Smart Contract chapter in the git book differs a bit from whats defined in the notion page in terms of naming and structure.

**Comment by tobikuhlmann** [comment]
thanks for the review, and yes, gitbook is now the updated structure without having updated everything in notion. Closing this issue as I also talked with Bogdan and Bayo about the structure
