### ISSUE TITLE
Write Mento Home section

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#30]
**Description**
- Landing page of the docs. 
- Uniswap-style explanation of Mento Labs, Protocol, Reserve, Mento.finance: https://docs.uniswap.org/concepts/overview

**Acceptance criteria**
- [x] Introduce the docs, tell readers what they will find and have quick links to what could be the most popular pages.

**Comment by tobikuhlmann** [comment]
pls review in GitBok: https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/mento-protocol/home

**Comment by bowd** [comment]
👍
