### ISSUE TITLE
Create smart contract class diagrams

### ISSUE THREAD

**Issue by tobikuhlmann** [mento-protocol/docs#31]
**Description**
For our smart contract documentation we need class diagrams with an explanation of EVERY function it contains, all state variables and structs. Bonus points for clean flow diagrams for logic that is not straight forward.
some diagrams have been started here: https://drive.google.com/file/d/1KOoYhVQs6r0dCqGWPav2niM73Zp7861l/view?usp=share_link

**Acceptance Criteria**
- C4 Class diagrams created for all core contracts

**Comment by bayological** [comment]
@tobikuhlmann @bowd I looked around the internets to see how detailed other protocols were going with their docs. I think this might be overkill. The only things I think we should show as a diagrams are the internals of the BiPool manager, as it's shown in the mcMint design doc, and the circuit breaker reset logic. We don't need additional issues for these as they both already exist. So if you two are happy with that let's close this.
