### ISSUE TITLE
[Q-4] Documentation improvements

### ISSUE THREAD

**Issue by bayological** [mento-protocol/docs#38]
**Description**

1. In the `BiPoolManager` docs page, the ***[[Executing Swaps](https://docs.mento.org/mento/developers/smart-contracts/bipoolmanager#executing-swaps)](https://docs.mento.org/mento/developers/smart-contracts/bipoolmanager#executing-swaps)*** section mentions the following:

> This function executes, in that it prices the swap and updates the virtual bucket sizes of the PoolExchange.
> 

However, it doesn’t consider the case where an exchange uses the `ConstantSumPricingModule`, which doesn’t update the bucket sizes on swaps.

1. On the Pricing Modules page, both pricing module links to GitHub are broken. Also, the [[constant sum pricing module formula](https://docs.mento.org/mento/developers/smart-contracts/pricing-modules#constantsumpricingmodule)](https://docs.mento.org/mento/developers/smart-contracts/pricing-modules#constantsumpricingmodule) should be updated to reflect the newly implemented value constant sum formula.

1. Some of the links included in the documentation pages are currently broken:
    - The config contract link is broken on the deployment parameters page: https://docs.mento.org/mento/developers/deployments/parameters
    - Github links in the `BreakerBox` section: https://docs.mento.org/mento/developers/smart-contracts/breakerbox

1. Consider adding documentation pages for the specific breaker contract implementations (`MedianDeltaBreaker` and `ValueDeltaBreaker`).

**Comment by bayological** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/phLg0LXAVa/estimate/8) in Sprint Poker #​​17

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ninocomputer** [comment]
I did the changes using [tobi's gitbook ](https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/changes/29/mento-protocol/home/~/details)account since for some reason the perms weren't updating for me. Also, requested reviews directly in the app.
