### ISSUE TITLE
Change the links of MU03 contracts form develop to master in the docs

### ISSUE THREAD

**Issue by ninocomputer** [mento-protocol/docs#40]
**Description**

Currently some links in mento docs point to the contracts on develop branch. After we've deployed everything on mainnet, we should go through the docs and update the links to point to contracts on main.

**Acceptance Criteria**

- [x] Links are updated and point to correct branch/contract

**Comment by ninocomputer** [comment]
also updated some other links that weren't fixed https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/changes/36/economics/risks/~/details

**Comment by baroooo** [comment]
Some issues I noticed:
- Mento twitter account link is broken:
https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/diff/~/changes/36/mento-protocol/quick-links
- Portal Token Bridge link is broken: https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/diff/~/changes/36/user-trading-guide/on-celo
- AddOracle() link does not point to main branch: https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/diff/~/changes/36/developers/smart-contracts/sortedoracles
- Links to config points to a commit and not the main branch: https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/diff/~/changes/36/economics/stability

**Comment by ninocomputer** [comment]
good catch on the first 2. With the last 2 issues even if you're pointing to main when you copy the line permalink it'll point to a specific commit. @baroooo

**Comment by baroooo** [comment]
cool, LGTM 👍

**Comment by nvtaveras** [comment]
👍
