### ISSUE TITLE
Update Docs to reference correct addresses

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/docs#42]
**Description**
As part of MU03, a couple of addresses have changed  we need to update our docs to reference the latest contract addresses these can be retrieved from the broadcast files in the deployment repo.

**Acceptance Criteria:**
- [x] baklava addresses are updated in docs 
- [x] alfajores addresses are updated in docs
- [x] once CGP is executes mainnet addresses are updated in docs

**Comment by baroooo** [comment]
Changes are ready for review:
https://app.gitbook.com/o/oiWI2eFpemrjyHvmX6xL/s/fHYZIGlFVI2XkPqpDQjn/~/changes/34/

Should not be merged until the deployed contracts are actually used.

**Comment by baroooo** [comment]
Changes are merged and live at https://docs.mento.org/mento/developers/deployments/addresses

**Comment by bayological** [comment]
@baroooo This looks good to me. I created [this issue](https://github.com/mento-protocol/docs/issues/43) to update the mainnet addresses. So once someone else has looked over this, we can move to done.

**Comment by baroooo** [comment]
Thanks @bayological. I believe @bowd already updated mainnet addresses in the docs. So current addresses should be good until we redeploy.

**Comment by baroooo** [comment]
will be fixed by: #46
