### ISSUE TITLE
Update Docs to reference updated StableTokenV2

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/docs#47]
**Description:**
This ticket is about updating all references to the StableToken implementation that will be outdated with MU04.

**Acceptance Criteria:**
- [x] addresses in docs are updated 
- [x] github code references are updated

**Comment by bowd** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/qptr4oiUec/estimate/9) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by philbow61** [comment]
assigned @denviljclarke & @baroooo to the gitbook changes

**Comment by baroooo** [comment]
LG ✅ 
curious, why the [reserve on baklava](https://explorer.celo.org/baklava/address/0x68Dd816611d3DE196FDeb87438B74A9c29fd649f/contracts#address-tabs) is not verified?
