### ISSUE TITLE
Remove Mento V1 related information

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/docs#48]
**Description**
With the deprecation of Mento V1, we can remove all Mento V1 references from our Mento Docs 

**Acceptance Criteria**
- [x] Mento V1 references are removed from docs e.g. exchange contract addresses, partial reserve references
- [x] Update smart contract diagram to remove v1
- [x] Look at all outside facing docs
- [ ] Add a note to the dune dashboard to mention V1 has been deprecated

**Comment by bowd** [comment]
Restructure the address page so that there's only one table, remove Mento V1 addresses
