### ISSUE TITLE
Update docs in Gitbook

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/docs#54]
## Description
Add section on Governance to the Gitbook.
Content for this section is available in [notion](https://www.notion.so/mentolabs/MENTO-token-documentation-58c4aeb0e2d245f2ae34b09225c928c3)

## Acceptance criteria

- [ ] There is a governance section at docs.mento.org with all the content from the notion page linked above

**Comment by bowd** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/vhz079RmcU/estimate/7) in Sprint Poker #​​37

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
